### PR TITLE
Additional actions

### LINKED ISSUE #1: when you make a move, you can't undo it.
When, for example, I mute my microphone by pressing the button I have configured, by pressing the same button again, I cannot mute my microphone. How can I make it work?

### LINKED ISSUE #6: [BUG] Gain value is no increasing in voicemeter
**Describe the bug**

**To Reproduce**
1. Go to add a new button and select "set strip parameter"
2. You select Gain and the strip number 
3. In the stream value you can use '+=3'
4. Voicemeter doesnt icrease in values of three

**Expected behavior**
Its suppouse to increase the values by three each time you touch the button but it doesnt work 

**Screenshots**
2020-11-17 23_37_07-deckboard

**Server App (please complete the following information):**
 - OS:Windows 10 
 - Version e.g. 1.9.80

**Client App (please complete the following information):**
 - OS: Android 9
 - Version [e.g. 1.9.73

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard
[log.log](https://github.com/rivafarabi/deckboard/files/5557994/log.log)
[log.log](https://github.com/rivafarabi/deckboard/files/5557995/log.log)
[database.zip](https://github.com/rivafarabi/deckboard/files/5558025/database.zip)

`)

**Additional context**

### PR DESCRIPTION
**Pull request by terenc3**
Add more actions, to toggle and increase or decrease values

Fixes #1, Fixes #6

### CODE REVIEW

**Comment by terenc3** [comment]
grafik

**Comment by astronaut954** [comment]
Greetings @terenc3, after a lot of time spent trying to install these additional actions I think the readme of your file is wrong or maybe you have inserted the wrong code inside it. As you can see the readme says to install the "deckboard-power-control", even if I change the paths and names to the voicemeeter-control it won't work, yet if I do exactly like you say in the readme and install the "deckboard-power-control" it will work (no errors shown in the install process log), but it's not the voicemeeter that is being installed. Can you help me?
04 05 21 -  06''34''04  - opera

**Comment by ZeeMoros** [comment]
Could you share your build by any chance ?

**Comment by terenc3** [comment]
You can download the extensions here https://roanapur.de/voicemeeter-control.asar and download it to %USERPROFILE%\deckboard\extensions. I don't know if it work on other machines, so make a backup of the original extension. However I've stopped investing time on deckboard, so i will not provide any further help.

**Comment by djony66** [comment]
any chance to add two icons for toggle? Like in streamlabs audio control.

**Comment by terenc3** [comment]
@djony66 Afaik deckboard does not provide an api to implement such thing

**Comment by AIO-Software-tech** [comment]
hi please can you fix this version for deckboard 2.0.5

Thank you

**Comment by terenc3** [comment]
@T0dCNg No i will not, because the author shows less activity in this project and also seems not to want to publish the sources of deckboard rivafarabi/deckboard#222. Furthermore I've ditched the project for that reason

**Pull request merged**
